// <auto-generated />
using HahnDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HahnWorkerService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250120202633_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HahnDataAccess.Domain.BreedAttributeBooleanModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<long>("_AttributeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttributeType")
                        .HasColumnOrder(1);

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "_AttributeType");

                    b.ToTable("BreedAttributeBoolean");
                });

            modelBuilder.Entity("HahnDataAccess.Domain.BreedAttributeRangeModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<long>("_AttributeType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttributeType")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Max")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Min")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "_AttributeType");

                    b.ToTable("BreedAttributeRange");
                });

            modelBuilder.Entity("HahnDataAccess.Domain.BreedModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Breed");
                });
#pragma warning restore 612, 618
        }
    }
}
